-- Enable Row Level Security (RLS) is recommended, but for this simple app we might start without it or with public access
-- For simplicity in this demo, we will allow public access (service_role key will bypass RLS anyway)

-- 1. Rooms Table
create table if not exists rooms (
  id bigint generated by default as identity primary key,
  name text not null,
  capacity integer not null,
  description text,
  image_url text,
  equipment text,
  created_at timestamptz default now()
);

-- 2. Bookings Table
create table if not exists bookings (
  id bigint generated by default as identity primary key,
  room_id bigint references rooms(id) on delete cascade not null,
  user_name text not null,
  title text,
  start_time timestamptz not null,
  end_time timestamptz not null,
  attendees integer default 0,
  applicant text,
  whatsapp text,
  description text,
  purpose text,
  status text default 'pending', -- pending, approved, rejected
  created_at timestamptz default now()
);

-- 3. Users Table
create table if not exists users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null, -- In production, use hashing!
  role text not null, -- super_admin, admin, user, viewer
  created_at timestamptz default now()
);

-- 4. Ads Table
create table if not exists ads (
  id bigint generated by default as identity primary key,
  type text not null, -- image, video
  url text not null,
  duration integer default 10,
  active boolean default true,
  created_at timestamptz default now()
);

-- 5. Settings Table
create table if not exists settings (
  key text primary key,
  value text,
  created_at timestamptz default now()
);

-- SEED DATA (Initial Data)

-- Rooms
insert into rooms (name, capacity, description, image_url, equipment)
values 
  ('Conference Room A', 12, 'Large conference room with projector and whiteboard.', 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1000', 'Projector, Whiteboard, Video Conf'),
  ('Meeting Room B', 6, 'Small meeting room for quick syncs.', 'https://images.unsplash.com/photo-1517502884422-41e157d44301?auto=format&fit=crop&q=80&w=1000', 'TV, Whiteboard'),
  ('Focus Pod 1', 1, 'Soundproof pod for individual work.', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=1000', 'Desk, Chair, Power Outlet'),
  ('Creative Lab', 8, 'Open space with bean bags and creative tools.', 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=1000', 'Whiteboard, Bean Bags, TV')
on conflict do nothing;

-- Users
insert into users (username, password, role)
values 
  ('superadmin', 'super123', 'super_admin'),
  ('admin', 'admin123', 'admin'),
  ('user', 'user123', 'user'),
  ('viewer', 'viewer123', 'viewer')
on conflict (username) do nothing;

-- Ads
insert into ads (type, url, duration)
values 
  ('image', 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80&w=1000', 10),
  ('image', 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&q=80&w=1000', 10)
on conflict do nothing;

-- Settings
insert into settings (key, value)
values ('running_text', 'Selamat Datang di RoomBook - Sistem Manajemen Ruang Meeting Modern')
on conflict (key) do nothing;
